# Generated by Django 4.1.3 on 2023-03-30 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='about',
            name='about_list',
        ),
    ]
