# Generated by Django 4.1.3 on 2023-09-07 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pro_app', '0002_remove_about_about_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='Demande',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=256)),
                ('prenom', models.CharField(max_length=256)),
                ('email', models.EmailField(max_length=254)),
                ('societe', models.CharField(max_length=256)),
                ('message', models.TextField()),
            ],
        ),
    ]
